version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"  # Astro frontend
      - "3001:3001"  # Hono API
    volumes:
      - ./data:/app/data  # SQLite database persistence
      - ./logs:/app/logs  # Application logs
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/anime.db
      - MAL_CLIENT_ID=${MAL_CLIENT_ID}
      - MAL_CLIENT_SECRET=${MAL_CLIENT_SECRET}
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates (if using HTTPS)
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - with-nginx

volumes:
  data:
  logs: